site_name: COVAS:NEXT
site_url: https://lucaelin.github.io/elite-dangerous-ai-integration
theme:
    name: material
markdown_extensions:
    - markdown.extensions.tables: {}
    - pymdownx.magiclink: {
          "repo_url_shortener": True,
          "repo_url_shorthand": True,
          "provider": "github",
          "user": "RatherRude",
          "repo": "Elite-Dangerous-AI-Integration"
      }
    - pymdownx.betterem: {}
    - pymdownx.tilde: {
          "subscript": False
      }
    - pymdownx.emoji: {
          "emoji_index": emoji.gemoji,
          "emoji_generator": emoji.to_png,
          "alt": "short",
          "options": {
              "attributes": {
                  "align": "absmiddle",
                  "height": "20px",
                  "width": "20px"
              },
              "image_path": "https://github.githubassets.com/images/icons/emoji/unicode/",
              "non_standard_image_path": "https://github.githubassets.com/images/icons/emoji/"
          }
      }
    - pymdownx.tasklist: {}
    - pymdownx.superfences: {}
    - pymdownx.saneheader: {}