site_name: COVAS:NEXT
site_url: https://lucaelin.github.io/elite-dangerous-ai-integration
theme:
    name: material
markdown_extensions:
    - markdown.extensions.tables: {}
    - pymdownx.magiclink: {
          "repo_url_shortener": True,
          "repo_url_shorthand": True,
          "provider": "github",
          "user": "RatherRude",
          "repo": "Elite-Dangerous-AI-Integration"
      }
    - pymdownx.betterem: {}
    - pymdownx.tilde: {
          "subscript": False
      }
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji 
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.tasklist: {}
    - pymdownx.superfences: {}