name: Build Executable

on: [push, pull_request]

jobs:
  pyinstaller-build:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest test -v

      - name: Install pyinstaller
        run: |
          $Env:PYINSTALLER_COMPILE_BOOTLOADER = "true"
          pip install --user --force-reinstall --ignore-installed --no-binary :all: pyinstaller==6.11.1

      - name: Determine paths for dependencies
        id: determine_paths
        run: |
          $ONNXRUNTIME_DLL = python -c 'import os, onnxruntime; print(os.path.join(os.path.dirname(onnxruntime.__file__), "capi", "onnxruntime_providers_shared.dll"))'
          $VAD_MODEL = python -c 'import os, pysilero_vad; print(os.path.join(os.path.dirname(pysilero_vad.__file__), "models", "silero_vad.onnx"))'
          $VEC_EXTENSION = python -c 'import os, sqlite_vec; print(os.path.join(os.path.dirname(sqlite_vec.__file__), "vec0.dll"))'
          echo "ONNXRUNTIME_DLL=$ONNXRUNTIME_DLL" >> $env:GITHUB_ENV
          echo "VAD_MODEL=$VAD_MODEL" >> $env:GITHUB_ENV
          echo "VEC_EXTENSION=$VEC_EXTENSION" >> $env:GITHUB_ENV
          python -c 'import onnxruntime; print("onnxruntime path:", onnxruntime.__file__)'
          python -c 'import pysilero_vad; print("pysilero_vad path:", pysilero_vad.__file__)'
          python -c 'import sqlite_vec; print("sqlite_vec path:", sqlite_vec.__file__)'

      - name: Debug environment variables
        run: |
          echo "ONNXRUNTIME_DLL=${{ env.ONNXRUNTIME_DLL }}"
          echo "VAD_MODEL=${{ env.VAD_MODEL }}"
          echo "VEC_EXTENSION=${{ env.VEC_EXTENSION }}"

      - name: Create Executable for AIGUI
        run: |
          pyinstaller .\src\AIGUI.py -y --onedir --clean --noconsole --add-data .\docs\screen\EDAI_logo.png:.\screen

      - name: Create Executable for Chat
        run: |
          pyinstaller .\src\Chat.py -y --onedir --clean --console --hidden-import=comtypes.stream --add-data .\src:. --add-data ${{ env.VAD_MODEL }}:.\pysilero_vad\models --add-binary ${{ env.ONNXRUNTIME_DLL }}:. --add-binary ${{ env.VEC_EXTENSION }}:.\sqlite_vec

      - name: Get current commit ID
        id: get_commit
        run: |
          $COMMIT_ID = git rev-parse HEAD
          echo "COMMIT_ID=$COMMIT_ID" >> $env:GITHUB_ENV

      - name: Create start.bat script
        run: |
          $commitId = "${{ env.COMMIT_ID }}"
          $start = "@echo off`r`nstart """" .\\AIGUI\\AIGUI.exe --chat=Chat\\Chat.exe --release=$commitId`r`nexit"
          $start | Out-File -Encoding ASCII .\\dist\\start.bat

      - name: Run e2e tests
        run: |
          python e2e/test_ChatExecutable.py

      - name: Run windows defender scan
        run: |
          & "C:\Program Files\Windows Defender\MpCmdRun.exe" -SignatureUpdate
          & "C:\Program Files\Windows Defender\MpCmdRun.exe" -Scan -ScanType 3 -File $PWD\dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: COVAS_NEXT_v${{ env.COMMIT_ID }}
          path: ./dist
