name: Build and Test Executable on linux

on: [push, pull_request]

jobs:
  pyinstaller-build:
    name: Build Executable
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          sudo apt-get install portaudio19-dev
          python -m pip install --upgrade pip setuptools
          python -m pip install --force-reinstall -r requirements.txt
          python -m pip install --force-reinstall numpy==2.2.2 opencv-python==4.10.0.84

      - name: Run tests
        run: |
          python -m pytest test -v

      - name: Install pyinstaller
        run: |
          python -m pip install pyinstaller@git+https://github.com/pyinstaller/pyinstaller.git@0d562b5

      - name: Determine paths for dependencies
        id: determine_paths
        run: |
          export VAD_MODEL=$(python3 -c 'import os, pysilero_vad; print(os.path.join(os.path.dirname(pysilero_vad.__file__), "models", "silero_vad.onnx"))')
          export VEC_EXTENSION=$(python3 -c 'import os, sqlite_vec; print(os.path.join(os.path.dirname(sqlite_vec.__file__), "vec0.so"))')
          echo "VAD_MODEL=$VAD_MODEL" >> $GITHUB_ENV
          echo "VEC_EXTENSION=$VEC_EXTENSION" >> $GITHUB_ENV

      - name: Create Executable for AIGUI
        run: |
          pyinstaller ./src/AIGUI.py -y --onedir --clean --noconsole --add-data ./docs/screen/EDAI_logo.png:./screen

      - name: Create Executable for Chat
        run: |
          pyinstaller ./src/Chat.py -y --onedir --clean --console --hidden-import=comtypes.stream `
            --add-data ./src:. `
            --add-binary ${{ env.VAD_MODEL }}:./pysilero_vad/models `
            --add-binary ${{ env.VEC_EXTENSION }}:./sqlite_vec

      - name: Create start.sh script
        run: |
          echo "#!/bin/bash" > ./dist/start.sh
          echo 'cd "$(dirname "$0")"' >> ./dist/start.sh
          echo "./AIGUI/AIGUI --chat=./Chat/Chat" >> ./dist/start.sh
          chmod +x ./dist/start.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: COVAS_NEXT_v${{ github.sha }}_linux
          path: ./dist
        # output the upload URL for later use
        id: upload-artifact

  e2e-and-scan:
    name: E2E Tests & Defender Scan
    runs-on: ubuntu-latest
    needs: pyinstaller-build
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: COVAS_NEXT_v${{ github.sha }}-linux
          path: dist

      - name: Run e2e tests
        run: |
          python --version
          python e2e/test_ChatExecutable.py
